import type { Metadata } from 'next';

export const SITE_DATA = {
  title: 'Neon Notes - Futuristic Notes App | Built by Devansh Sharma',
  description:
    'Neon Notes is a futuristic, neon-themed notes app for capturing ideas, drafts, reminders, and structured writing in a private, organized workspace.',
  url: 'https://neon-notes.vercel.app',
  aliases: [
    'https://neon-notes.vercel.app',
    'https://visarnote.vercel.app',
    'https://visarnotes.vercel.app',
    'https://notesneon.vercel.app',
  ],
  author: 'Devansh Sharma',
  brand: 'RootDeveloperDS',
  logoPath: '/og-image.svg',
  contact: {
    email: 'developersofroot@gmail.com',
  },
  social: {
    website: 'https://rootdeveloperds.odoo.com/',
    portfolio: 'https://devanshsharma.vercel.app',
    github: 'https://github.com/RootDeveloperDS',
    linkedin: 'https://www.linkedin.com/in/devanshsharma987',
    x: 'https://x.com/devanshsha6563',
  },
};

export const PRODUCT_DATA = {
  name: 'Neon Notes',
  category: 'ProductivityApplication',
  os: 'Web',
  author: SITE_DATA.author,
  publisher: SITE_DATA.brand,
  description:
    'Neon Notes is a neon-themed notes workspace for creating, editing, and managing notes with secure authentication and a futuristic interface.',
  website: SITE_DATA.url,
  logoPath: '/og-image.svg',
  bannerPath: '/og-image.svg',
  pricing: '0',
  priceType: 'Free',
  priceCurrency: 'USD',
};

const siteUrl = new URL(process.env.NEXT_PUBLIC_SITE_URL ?? SITE_DATA.url);
const siteName = PRODUCT_DATA.name;
const creatorHandle = '@devanshsha6563';

const keywords = [
  PRODUCT_DATA.name,
  'neon notes app',
  'online notes app',
  'notes organizer',
  'secure note taking',
  'personal knowledge base',
  'digital notebook',
  'private notes',
  'study notes',
  'work notes',
  'idea capture',
  'task notes',
  'memo app',
  'futuristic notes',
  'dark mode notes',
  'markdown notes',
  'cloud notes',
  'notes dashboard',
  'notes manager',
  'productivity app',
  'writing workspace',
  'second brain',
  'note vault',
  'searchable notes',
  'firebase notes app',
  'Next.js notes app',
  'react productivity app',
  'web app for notes',
  'neon ui',
  'futuristic productivity',
  'secure personal notes',
  'web notebook',
  'online notebook',
  'organized note storage',
  'note keeping app',
  'idea management',
  'knowledge management',
  'note taking platform',
  'note organizer',
  'note archive',
  'digital notes',
  'neon productivity',
  'neon aesthetic',
  'secure writing app',
  'online memo',
  'note system',
  'lightweight notes',
  'fast notes',
  'smart notes',
  'idea journal',
  'daily notes',
  SITE_DATA.author,
  SITE_DATA.brand,
  'RootDeveloperDS',
  'Devansh Sharma',
  'developerofroot',
  'devanshsha6563',
  'notes web app',
  'notes SaaS',
  'cloud notebook',
  'note vault app',
  'productivity tools',
  'creative notes',
  'structured notes',
  'neon-notes.vercel.app',
  'visarnote.vercel.app',
  'visarnotes.vercel.app',
  'notesneon.vercel.app',
];

const ogImage = {
  url: PRODUCT_DATA.bannerPath,
  width: 1200,
  height: 630,
  alt: `${siteName} - futuristic notes and productivity workspace`,
};

export const metadata: Metadata = {
  metadataBase: siteUrl,
  applicationName: siteName,
  title: {
    default: SITE_DATA.title,
    template: `%s | ${siteName}`,
  },
  description: PRODUCT_DATA.description,
  generator: 'Next.js',
  keywords,
  authors: [{ name: SITE_DATA.author, url: SITE_DATA.social.portfolio }],
  creator: SITE_DATA.author,
  publisher: PRODUCT_DATA.publisher,
  category: 'productivity',
  classification: 'Notes and productivity application',
  referrer: 'origin-when-cross-origin',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: SITE_DATA.url,
    languages: {
      'en-US': '/',
      en: '/',
    },
  },
  icons: {
    icon: '/favicon.ico',
    shortcut: '/favicon.ico',
  },
  openGraph: {
    title: SITE_DATA.title,
    description: PRODUCT_DATA.description,
    url: SITE_DATA.url,
    type: 'website',
    siteName,
    locale: 'en_US',
    images: [ogImage],
  },
  twitter: {
    card: 'summary_large_image',
    title: SITE_DATA.title,
    description: PRODUCT_DATA.description,
    creator: creatorHandle,
    site: creatorHandle,
    images: [ogImage.url],
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'google902e925a0f1e29e0',
  },
  themeColor: '#050816',
  other: {
    'owner': PRODUCT_DATA.publisher,
    'designer': SITE_DATA.author,
    'author': SITE_DATA.author,
    'application-name': PRODUCT_DATA.name,
    'application-category': PRODUCT_DATA.category,
    'application-platform': PRODUCT_DATA.os,
    'price': PRODUCT_DATA.pricing,
    'price-currency': PRODUCT_DATA.priceCurrency,
    'contact:email': SITE_DATA.contact.email,
    'msapplication-TileColor': '#050816',
    'theme-color': '#050816',
    'color-scheme': 'dark',
    'twitter:dnt': 'on',
    'official-domain': 'https://neon-notes.vercel.app',
    'domain-alias-1': 'https://visarnote.vercel.app',
    'domain-alias-2': 'https://visarnotes.vercel.app',
    'domain-alias-3': 'https://notesneon.vercel.app',
  },
};

export const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: PRODUCT_DATA.publisher,
  url: SITE_DATA.social.website,
  email: SITE_DATA.contact.email,
  sameAs: [
    SITE_DATA.social.website,
    SITE_DATA.social.portfolio,
    SITE_DATA.social.github,
    SITE_DATA.social.linkedin,
    SITE_DATA.social.x,
    ...SITE_DATA.aliases,
  ],
  founder: {
    '@type': 'Person',
    name: SITE_DATA.author,
    url: SITE_DATA.social.portfolio,
  },
  brand: {
    '@type': 'Brand',
    name: PRODUCT_DATA.name,
  },
  description: SITE_DATA.description,
};

export const websiteJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: PRODUCT_DATA.name,
  url: SITE_DATA.url,
  description: PRODUCT_DATA.description,
  author: {
    '@type': 'Person',
    name: SITE_DATA.author,
    url: SITE_DATA.social.portfolio,
  },
  publisher: {
    '@type': 'Organization',
    name: PRODUCT_DATA.publisher,
    url: SITE_DATA.social.website,
  },
  sameAs: SITE_DATA.aliases,
};

export const softwareApplicationJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  name: PRODUCT_DATA.name,
  description: PRODUCT_DATA.description,
  applicationCategory: PRODUCT_DATA.category,
  operatingSystem: PRODUCT_DATA.os,
  author: {
    '@type': 'Person',
    name: SITE_DATA.author,
    url: SITE_DATA.social.portfolio,
    sameAs: [
      SITE_DATA.social.website,
      SITE_DATA.social.portfolio,
      SITE_DATA.social.github,
      SITE_DATA.social.linkedin,
      SITE_DATA.social.x,
    ],
  },
  publisher: {
    '@type': 'Organization',
    name: PRODUCT_DATA.publisher,
    url: SITE_DATA.social.website,
  },
  url: SITE_DATA.url,
  sameAs: SITE_DATA.aliases,
  image: [`${SITE_DATA.url}${PRODUCT_DATA.logoPath}`],
  offers: {
    '@type': 'Offer',
    price: PRODUCT_DATA.pricing,
    priceCurrency: PRODUCT_DATA.priceCurrency,
    availability: 'https://schema.org/InStock',
    url: SITE_DATA.url,
  },
  featureList: [
    'Neon-themed interface',
    'Secure authentication',
    'Create, edit, and manage notes',
    'Organized notes dashboard',
    'Cloud-backed data storage',
    'Responsive web experience',
  ],
  softwareRequirements: 'Modern web browser and internet connection',
};
